homepage:
    path:     /{_locale}
    defaults: { _controller: GingyCoreBundle:Homepage:index }
    requirements:
        _locale: en|de

imprint:
    path:     /{_locale}/imprint
    defaults: { _controller: GingyCoreBundle:Homepage:imprint }
    requirements:
        _locale: en|de

organisation_add:
    path:     /{_locale}/organisation/add
    defaults: { _controller: GingyCoreBundle:Organisation:add }
    requirements:
        _locale: en|de