services:
    gingy_user.registration.form.type:
        class: Gingy\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: gingy_user_registration }
    gingy_user.profile.form.type:
        class: Gingy\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: gingy_user_profile }